name: ecommerce_intelligence
version: "1.0.0"
config-version: 2

profile: ecommerce_intelligence
model-paths: ["models"]
test-paths: ["dbt_tests"]

clean-targets:
  - target
  - dbt_packages

models:
  ecommerce_intelligence:
    +materialized: view